# Generated by Django 4.2.30 on 2026-05-11 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_range", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("us_state", models.CharField(blank=True, max_length=2)),
                ("gender", models.CharField(blank=True, max_length=30)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("saved_zipcode", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["username"],
                "indexes": [
                    models.Index(
                        fields=["username"], name="accounts_us_usernam_32dcf6_idx"
                    )
                ],
            },
        ),
    ]
