# Generated by Django 4.2.30 on 2026-05-11 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cast_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mock_votes",
                        to="elections.candidate",
                    ),
                ),
                (
                    "measure_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mock_votes",
                        to="elections.measureoption",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_votes",
                        to="elections.race",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-cast_at"],
                "indexes": [
                    models.Index(fields=["race"], name="voting_mock_race_id_5459e1_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="mockvote",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("candidate__isnull", False), ("measure_option__isnull", True)
                    ),
                    models.Q(
                        ("candidate__isnull", True), ("measure_option__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="exactly_one_vote_target",
            ),
        ),
    ]
