# Generated by Django 4.2.30 on 2026-05-11 17:51

from django.db import migrations, models


def dedupe_mock_votes(apps, schema_editor):
    MockVote = apps.get_model('voting', 'MockVote')
    duplicate_groups = (
        MockVote.objects.values('user_id', 'race_id')
        .annotate(vote_count=models.Count('id'))
        .filter(vote_count__gt=1)
    )

    for group in duplicate_groups:
        duplicates = MockVote.objects.filter(user_id=group['user_id'], race_id=group['race_id']).order_by('cast_at', 'id')
        keeper = duplicates.first()
        duplicates.exclude(pk=keeper.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mockvote",
            name="voting_mock_race_id_5459e1_idx",
        ),
        migrations.AddIndex(
            model_name="mockvote",
            index=models.Index(
                fields=["race", "cast_at"], name="voting_mock_race_id_b4b189_idx"
            ),
        ),
        migrations.RunPython(dedupe_mock_votes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="mockvote",
            constraint=models.UniqueConstraint(
                fields=("user", "race"), name="unique_user_race_vote"
            ),
        ),
    ]
