# Generated by Django 4.2.30 on 2026-05-11 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityRace",
            fields=[],
            options={
                "verbose_name": "Community race",
                "verbose_name_plural": "Community races",
                "ordering": ["submitted_at"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("elections.race",),
        ),
        migrations.RenameField(
            model_name="race",
            old_name="submitted_by",
            new_name="submitter",
        ),
        migrations.AddField(
            model_name="race",
            name="ballot_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="race",
            name="community_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending_review", "Pending Review"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="location_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="race",
            name="moderator_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="race",
            name="no_vote_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="race",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="race",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="race",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_races",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="source_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="race",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="race",
            name="supporting_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="race",
            name="yes_vote_details",
            field=models.TextField(blank=True),
        ),
    ]
