# Generated by Django 4.2.30 on 2026-05-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0002_communityrace_rename_submitted_by_race_submitter_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cycle_year", models.IntegerField(unique=True)),
                ("description", models.CharField(blank=True, max_length=100)),
                ("cycle_start", models.DateField()),
                ("cycle_end", models.DateField()),
            ],
            options={
                "ordering": ["-cycle_year"],
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="bioguide_id",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name="candidate",
            name="contact_office",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="candidate",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="candidate",
            name="fec_candidate_id",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name="candidate",
            name="openstates_person_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="candidate",
            name="source_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="race",
            name="match_confidence",
            field=models.CharField(
                blank=True,
                choices=[
                    ("verified", "Verified"),
                    ("high", "High"),
                    ("medium", "Medium"),
                    ("low", "Low"),
                    ("flagged", "Flagged for Review"),
                ],
                default="verified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="race",
            name="source_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="race",
            name="source",
            field=models.CharField(
                choices=[
                    ("civic_api", "Civic API"),
                    ("community", "Community"),
                    ("openelections", "OpenElections"),
                    ("medsl", "MEDSL"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DistrictRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=2)),
                ("district_type", models.CharField(max_length=50)),
                ("district_number", models.CharField(blank=True, max_length=20)),
                ("ocd_division_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("fips_code", models.CharField(blank=True, max_length=20)),
                ("election_year_valid", models.IntegerField(blank=True, null=True)),
                ("approximate", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["state", "district_type"],
                        name="elections_d_state_3a1749_idx",
                    )
                ],
                "unique_together": {("ocd_division_id", "election_year_valid")},
            },
        ),
        migrations.AddField(
            model_name="election",
            name="election_cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="elections",
                to="elections.electioncycle",
            ),
        ),
    ]
