# Generated by Django 4.2.30 on 2026-05-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_electioncycle_candidate_bioguide_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="external_race_id",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
