# Generated by Django 4.2.30 on 2026-05-13 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_electioncycle_candidate_bioguide_id_and_more"),
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="synclog",
            name="cycle_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="synclog",
            name="records_skipped",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="SourceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("civic", "Google Civic"),
                            ("fec", "OpenFEC"),
                            ("congress", "Congress Legislators"),
                            ("openstates", "Open States"),
                            ("census", "U.S. Census"),
                            ("openelections", "OpenElections"),
                            ("medsl", "MEDSL"),
                        ],
                        max_length=30,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("raw_payload", models.JSONField()),
                ("payload_checksum", models.CharField(max_length=64)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_records",
                        to="elections.candidate",
                    ),
                ),
                (
                    "linked_race",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_records",
                        to="elections.race",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "external_id"],
                        name="ops_sourcer_source_1047e5_idx",
                    ),
                    models.Index(
                        fields=["linked_race"], name="ops_sourcer_linked__af589c_idx"
                    ),
                ],
                "unique_together": {("source", "external_id")},
            },
        ),
    ]
